### PR TITLE
[WIP] Added prettier button

### PR DESCRIPTION
**Pull request by phil-r**
It takes current code and formats it using `prettier`
Shortcut is `Ctrl + Alt + F` (as in `prettier-atom`)

image

### CODE REVIEW

**Comment by voronianski** [comment]
@phil-r also some hot keys will be nice to have :)

**Comment by phil-r** [comment]
@voronianski I just wanted to have a big orange button ;) I'll move it to actions and will look into hotkeys ;)

**Comment by phil-r** [comment]
@voronianski PR updated

**Comment by voronianski** [comment]
@phil-r awesome! thanks!

**Pull request merged**
